name: ebay_search
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  tuple: ^2.0.0
  fort: ^0.1.2
  feed: ^0.3.31

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - config/ #Imports the configuration files with application secrets

